// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeaJ5joEN8e1zhUkfhp2NOSc38Z_bHbk',
    appId: '1:631554133609:web:897288a8ae6f10fa231cf8',
    messagingSenderId: '631554133609',
    projectId: 'meddoseapp-a1890',
    authDomain: 'meddoseapp-a1890.firebaseapp.com',
    storageBucket: 'meddoseapp-a1890.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOS9tjh2vf7wIED5aXljj-bL-8R4Kum4',
    appId: '1:631554133609:android:634d46097ae7dc31231cf8',
    messagingSenderId: '631554133609',
    projectId: 'meddoseapp-a1890',
    storageBucket: 'meddoseapp-a1890.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQOwNiMRofoGCAbBNDbbOj0kukPwC8xuo',
    appId: '1:631554133609:ios:2a6aed7acf15ecf7231cf8',
    messagingSenderId: '631554133609',
    projectId: 'meddoseapp-a1890',
    storageBucket: 'meddoseapp-a1890.appspot.com',
    iosBundleId: 'com.example.meddoseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQOwNiMRofoGCAbBNDbbOj0kukPwC8xuo',
    appId: '1:631554133609:ios:2a6aed7acf15ecf7231cf8',
    messagingSenderId: '631554133609',
    projectId: 'meddoseapp-a1890',
    storageBucket: 'meddoseapp-a1890.appspot.com',
    iosBundleId: 'com.example.meddoseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeaJ5joEN8e1zhUkfhp2NOSc38Z_bHbk',
    appId: '1:631554133609:web:f7e384a16cf2f115231cf8',
    messagingSenderId: '631554133609',
    projectId: 'meddoseapp-a1890',
    authDomain: 'meddoseapp-a1890.firebaseapp.com',
    storageBucket: 'meddoseapp-a1890.appspot.com',
  );
}
